#pragma once

#define VERSION_MAJOR 0
#define VERSION_MINOR 2
#define VERSION_PATCH 2

#define VERSION_STRINGIFY_IMPL(x) #x
#define VERSION_STRINGIFY(x) VERSION_STRINGIFY_IMPL(x)

#define VERSION_STRING               \
    VERSION_STRINGIFY(VERSION_MAJOR) \
    "." VERSION_STRINGIFY(VERSION_MINOR) "." VERSION_STRINGIFY(VERSION_PATCH)
