#pragma once

// Patch-proof token-slot discovery.
//
// Token IDs for shader properties (e.g. `_dyeingColorMaskR`) are
// re-bucketed by the engine's string-interner every patch. The slot
// ADDRESS that stores the token id, however, is generated by the
// compiler from the registrar function and changes only when the
// game binary itself is rebuilt with a different layout.
//
// This module scans the loaded module's executable regions for the
// adjacent-lea pattern emitted by every registrar call:
//
//     lea rcx, [rip+disp32]      ; lea rcx, [table_slot]
//     lea rdx, [rip+disp32]      ; lea rdx, [name_string]
//     ... mov r8d,1; mov r9d,196607; call interner ...
//
// For every match whose `rdx` target points to a known dye-property
// name string, we record `(slot_addr, layer, channel)`. At classify
// time we walk the list, read each slot's live u32 value, and
// return the layer/channel of any slot equal to the incoming token.
//
// Multiple registrar tables (Table A `dword_146173160`, Table B
// `dword_1461730E0`, and any future ones) are picked up
// automatically because each registrar emits the same pattern with
// a different slot target.

#include <cstddef>
#include <cstdint>

namespace Transmog::ColorOverride::TokenSlotDiscovery
{
    /// One-shot module-init pass. Safe to call multiple times; only
    /// the first call performs the scan.
    void run();

    /// True after `run()` has finished its scan (whether or not it
    /// discovered any slots).
    bool is_complete() noexcept;

    /// Classify a token by reading discovered slots. Returns:
    ///   0 = tint, 1 = mask, 2 = detail, 3 = hair, -1 = no match.
    int classify_layer(std::uint32_t tok) noexcept;

    /// Channel kind: 0=R, 1=G, 2=B, -1 = none.
    int classify_channel(std::uint32_t tok) noexcept;

    /// Live token id for a property name (or 0 if not discovered /
    /// slot reads 0). Used by persistence reload paths.
    std::uint32_t lookup_token_for_name(const char *name) noexcept;

    /// Reverse: find the property NAME for a live token id. Returns
    /// `nullptr` if no discovered slot matches. The returned pointer
    /// is a static string literal; safe to compare with strcmp or
    /// hand to a logger.
    const char *name_for_token(std::uint32_t tok) noexcept;

    /// Number of `(slot_addr, name)` pairs discovered. Diagnostic.
    std::size_t slot_count() noexcept;
}
