#pragma once

// Engine string-interner hook.
//
// `sub_140F46680(u32* dest, const char* name, int, u32 sentinel)` is the engine's master name-interning function. It
// assigns (or looks up cached) u32 token ids for shader-property names. We hook it to capture every `(name, token_id)`
// pair so `token_label_for(tokenId)` and `token_id_for_name(name)` can resolve names that aren't in the AOB-discovered
// static slot tables.
//
// Patch-proof: AOB anchored on the function prologue. Tokens generated by ANY engine code path (not just the registrar
// tables our discovery walks) are captured.

#include <cstddef>
#include <cstdint>

namespace Transmog::ColorOverride::InternerHook
{
    /**
     * One-shot install. Returns true on successful hook install. Safe to call multiple times; only the first call
     * hooks.
     */
    bool init() noexcept;

    /**
     * Re-walk the engine's interner entries array if our captured set looks stale (fewer entries than the engine
     * currently has, or the table has been re-allocated). Throttled internally; safe to call from a hot path. Returns
     * the number of newly-captured (name, token) pairs.
     */
    std::size_t refresh() noexcept;

    /**
     * Reverse lookup: token id -> property name. Returns nullptr if
     * the token wasn't observed via the interner. The returned pointer is the engine's own .rdata string
     * (process-lifetime stable).
     */
    const char *name_for_token(std::uint32_t tok) noexcept;

    /// Forward lookup: name -> token id. Returns 0 if not observed.
    std::uint32_t token_for_name(const char *name) noexcept;

    /// Number of (name, token) pairs captured. Diagnostic.
    std::size_t capture_count() noexcept;
} // namespace Transmog::ColorOverride::InternerHook
