#ifndef TRANSMOG_VERSION_HPP
#define TRANSMOG_VERSION_HPP

#define VERSION_MAJOR 0
#define VERSION_MINOR 4
#define VERSION_PATCH 0

#define VERSION_STRINGIFY_IMPL(x) #x
#define VERSION_STRINGIFY(x) VERSION_STRINGIFY_IMPL(x)

#define VERSION_STRING               \
    VERSION_STRINGIFY(VERSION_MAJOR) \
    "." VERSION_STRINGIFY(VERSION_MINOR) "." VERSION_STRINGIFY(VERSION_PATCH)

#endif // TRANSMOG_VERSION_HPP
